export const StatusResponse = {
  SUCCESS: 1,
  FAIL: 2,
  FOBBIDEN: 3,
  NOTFOUND: 4,
  EXISTS_USERNAME: 5,
  EXISTS_EMAIL: 6,
  NOT_EXISTS_ROLE: 8,
  USERNAME_OR_PASSWORD_IS_NOT_CORRECT: 9,
  PASSWORD_INCORRECT: 17,
  NOT_EXIST_EMAIL: 18,
  WRONG_OTP: 19,
  WRONG_HASH_CODE: 20,
};
